name: Build and Push Backend & Frontend Images

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Backend Image (local)
        run: |
          docker build \
            -t backend-temp:latest \
            -f src/week2/backend/Dockerfile src/week2/backend

      - name: Build Frontend Image (local)
        run: |
          docker build \
            -t frontend-temp:latest \
            -f src/week2/frontend/Dockerfile src/week2/frontend

  push:
    name: Push Docker Images to DockerHub
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Backend Image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/myapp-backend:latest \
            -f src/week2/backend/Dockerfile \
            --push src/week2/backend

      - name: Build & Push Frontend Image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/myapp-frontend:latest \
            -f src/week2/frontend/Dockerfile \
            --push src/week2/frontend
